### PR TITLE
spread: refresh alpine

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
```
Run snap run spread-mir-ci.spread -v lxd:alpine-3.18:...:gcc
2024-06-03 08:47:25 Found /home/runner/work/wlcs/wlcs/spread.yaml.
error: nothing matches provider filter
```

**Comment by Saviq** [comment]
> ```
> Run snap run spread-mir-ci.spread -v lxd:alpine-3.18:...:gcc
> error: nothing matches provider filter
> ```

Ah, multiple sources of truth, I challenge you!

**Comment by Saviq** [comment]
Dropped the clang fix, as it doesn't, actually… need this to get fixed on noble:

https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-18/+bug/2064187

**Review by AlanGriffiths — APPROVED** [review]
Sure

**Pull request merged**
